name: 01-Firstworkflow
on:
    push:
      branches:
        - 'main'
    workflow_dispatch:
jobs:
    joaquin:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Hello world'
            
